// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsO-POnnJ-u84-j8aDRipBb654Hu9ftdY',
    appId: '1:828300936239:web:bf4877b7c6862d0a4032da',
    messagingSenderId: '828300936239',
    projectId: 'absolute-journal',
    authDomain: 'absolute-journal.firebaseapp.com',
    storageBucket: 'absolute-journal.firebasestorage.app',
    measurementId: 'G-D6GNMHYXDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29bSPRucYWOV8OarBbkGix_0_hATWwNE',
    appId: '1:828300936239:android:fcd8daf2d23fd3a04032da',
    messagingSenderId: '828300936239',
    projectId: 'absolute-journal',
    storageBucket: 'absolute-journal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV4pOVFAM9P0qzg2cXt3ECyUD5fXUZdq0',
    appId: '1:828300936239:ios:be87b062d1d2caa04032da',
    messagingSenderId: '828300936239',
    projectId: 'absolute-journal',
    storageBucket: 'absolute-journal.firebasestorage.app',
    iosClientId:
        '828300936239-2rstuakmltkifn4vvl2vpq058fceubff.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV4pOVFAM9P0qzg2cXt3ECyUD5fXUZdq0',
    appId: '1:828300936239:ios:be87b062d1d2caa04032da',
    messagingSenderId: '828300936239',
    projectId: 'absolute-journal',
    storageBucket: 'absolute-journal.firebasestorage.app',
    iosClientId:
        '828300936239-2rstuakmltkifn4vvl2vpq058fceubff.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsO-POnnJ-u84-j8aDRipBb654Hu9ftdY',
    appId: '1:828300936239:web:9f8b43aa16e6dc7b4032da',
    messagingSenderId: '828300936239',
    projectId: 'absolute-journal',
    authDomain: 'absolute-journal.firebaseapp.com',
    storageBucket: 'absolute-journal.firebasestorage.app',
    measurementId: 'G-E0Z1NKVD94',
  );
}
